Mybranch
ClevertecFrontendLab/sprint2-Evgeny-Kochetkov pull request #7
Opened 2023-02-08 15:31 UTC by Evgeny-Kochetkov

2023-02-08 15:35 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675870510/slider%20one%20foto%20768px.png)

2023-02-08 17:09 UTC, Ivan6813 requested changes

2023-02-08 17:09 UTC, Ivan6813 commented on src/components/book/index.js
> +                    bookingProp={booking}
какое-то слишком большое расстояние между блоками

![msedge_b90UavMSuX](https://user-images.githubusercontent.com/79784960/217601755-d67186fe-c91d-4b18-8716-8e3b454d8039.png)

2023-02-09 11:20 UTC, Evgeny-Kochetkov commented
![2](https://user-images.githubusercontent.com/91734579/217798891-0c65f070-a7d9-483c-b7a8-33652bdc3e96.jpg)
![1](https://user-images.githubusercontent.com/91734579/217798921-1952ccdc-f1bc-490e-9743-ededa50c68c9.jpg)

2023-02-09 11:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test button comment view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/Test%20width%201440px%20--%20test%20button%20comment%20view%20(failed).png)
***
**Test width 1440px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/Test%20width%201440px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/app.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20after%20768px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20before%20768px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20not%20foto%20768px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675941688/slider%20one%20foto%20768px.png)

2023-02-09 11:22 UTC, Evgeny-Kochetkov commented
Оставил комментарий выше, спасибо за уделенное время))

2023-02-09 11:30 UTC, Ivan6813 approved these changes

2023-02-09 11:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Evgeny-Kochetkov/1675942830/slider%20one%20foto%20768px.png)

2023-02-09 11:50 UTC, merged